language: node_js
node_js:
- stable
script:
- npm test
after_success: npm run coverage
deploy:
  app : questioner
  provider: heroku
  api_key:
    secure: TYwnHCiVNmeQTAyiPzEjtuatruteLm1Jv0Fbu53kBC7UtsqAi3zlLxT/wLEaqFRrX6GCaurVXeMc9lIlTG2j/Cor+chHMQKr6L6/WH5vJQA57yyBew+2csLa+PTOjnYYn9ZL1W8eh/QDeCkwm9KNXw+HfbLIASY0veyx6HNRnOjkizN1pfSw5ZO0cEF2UUl5p6vasenj1WTAfUYMZnfj6pOzdxzTYGRcAsr2PIX+g2SzhfBkfZ5CvCDGBevl574WkjZRS2EqPJxSwx7zWJArMH81TMgkBEtrLJvtcOWBrCq55erZgcSim/YI0XxSqB5e3kwreCnkmgKz2dPsX+HdpPiy9wU2ObqlQ+t7BSBRP6ZSL7oQ/LSylwmuff2UG6daxILItMwx6vutsbXtrT8U+4YRhv7RGBmc+h/jeRZ+Wvo3wdSKoh1BZR63eZAwZv7/tKLXMqxolUmyI3fO5GwvES2B65MZRsHXvgoXJrzRqRejyFOW+eYBFvokarY1MX9v1gx9oYzFMLGwfmlq2IVPI4m23k4PzkOvM7Sn1eNCFi0nEcJAZ9nEahTDK+NXL6cvhboR56Tal6lCXpRDwJiA1N87qe00k/0DHQWWJzcy5M8SQLFMyJ4Mv+TTyStnnR5MdHL2bOHtBT+zhPAagAZFR+6mV+lD+ILak9G/gDOT6hE=
    on : ch-refactor-resources-endpoints-163054764